### ISSUE TITLE
search does not require authentication

### ISSUE THREAD

**Issue by 4cq2** [n0madic/twitter-scraper#101]
If you use the Android app for example, you can search without authentication. monitoring the requests returns this:

~~~
GET /2/search/adaptive.json?cards_platform=Android-12&earned=true&ext=mediaRestrictions%2CaltText%2CmediaStats%2CmediaColor%2Cinfo360%2ChighlightedLabel%2ChasNftAvatar%2CunmentionInfo%2CeditControl%2CpreviousCounts%2ClimitedActionResults%2CsuperFollowMetadata&include_blocked_by=true&include_blocking=true&include_cards=true&include_carousels=true&include_composer_source=true&include_entities=true&include_ext_birdwatch_pivot=true&include_ext_edit_control=true&include_ext_has_nft_avatar=true&include_ext_is_blue_verified=true&include_ext_is_blue_verified=true&include_ext_is_tweet_translatable=true&include_ext_is_tweet_translatable=true&include_ext_limited_action_results=true&include_ext_media_availability=true&include_ext_previous_counts=true&include_ext_professional=true&include_ext_profile_image_shape=true&include_ext_profile_image_shape=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&include_ext_verified_type=true&include_ext_verified_type=true&include_ext_views=true&include_media_features=true&include_profile_interstitial_type=true&include_quote_count=true&include_reply_count=true&include_user_entities=true&include_viewer_quick_promote_eligibility=true&q=filter%3Aspaces&query_source=typed_query&simple_quoted_tweet=true&spelling_corrections=true&tweet_mode=extended&tweet_search_mode=top HTTP/1.1
Host: api.twitter.com
Authorization: OAuth oauth_consumer_key="3nVuSoBZnx6U4vzUxf5w",oauth_nonce="5775992602006906429184916339582",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1684614059",oauth_version="1.0",oauth_token="1660017733327630336-FClvhvGL5hO3eahU1O2cuCBHbEwOyc",oauth_signature="I64WGB%2BOG0Pe87pCKzi4w091w2w%3D"
~~~

**Comment by n0madic** [comment]
This package uses the frontend API
endpoint: https://twitter.com/i/api/2/search/adaptive.json

**Comment by 4cq2** [comment]
OK, but are you willing to throw away anonymous support just because you dont want to consider other clients?

**Comment by n0madic** [comment]
Suggest an example of anonymous search without OAuth authorization like in this issue

**Comment by 4cq2** [comment]
OK, I guess I will write the code myself. I know its possible using Android credentials:

~~~go
identifier = "3nVuSoBZnx6U4vzUxf5w"
password = "Bcs59EFbbsdF6Sl9Ng71smgStWEGwXXKSjYvPVt7qys"
~~~

for anonymous access. but it seems you are not interested.

**Comment by n0madic** [comment]
I am not aware of this method - can you elaborate?

**Comment by 4cq2** [comment]
I am still researching the solution. I was hoping someone has the code already, but I guess I need to write it.

**Comment by omertoast** [comment]
Is there any updates on this issue? I'm working on a project that it's not possible for a user to authenticate.

**Comment by 4cq2** [comment]
I found a working solution, however I have already been privately contacted once by a scammer, so I am not going to speak any more publicly on the matter. If you wish to contact me privately go ahead.

**Comment by 4cq2** [comment]
note the above user @omertoast wants this feature implemented so that they can use it with their private, company software:

> ![Untitled](https://github.com/n0madic/twitter-scraper/assets/126826528/f57af08c-b246-4e8f-9cc8-1ec10f799b5a)

I have implemented the new anonymous authentication, but I did not do it so that companies could get free code off my back. I am closing this. If someone has PUBLIC TWITTER code, then contact me for free help. otherwise for people with private code, I only offer paid support.

**Comment by omertoast** [comment]
let me implement it myself weirdo

**Comment by 4cq2** [comment]
@omertoast has now been blocked for off topic comments. they wont be able to comment further.

**Comment by 4cq2** [comment]
> i didnt asked for a free help, i asked you if there is an example solution. nvm let me implement it myself weirdo

@omertoast has now been blocked for off topic comments. Also this is type business gaslighting. they are asking for my time, without offering any money. THIS IS FREE HELP. please anyone visiting this page dont let companies trick you into giving your time out for free.

**Comment by karashiiro** [comment]
soooo... were you planning on releasing that example? More than one person in the world can make use of this (I maintain a [TypeScript port](https://github.com/the-convocation/twitter-scraper) of this library and the auth requirement is concerning for CI).

**Comment by 4cq2** [comment]
sorry but because of the actions of @omertoast - I am forced to do any further communication privately. feel free to contact me with the info on my user page.

**Comment by 4cq2** [comment]
https://github.com/n0madic/twitter-scraper/issues/100
