### ISSUE TITLE
Missing =

### ISSUE THREAD

**Issue by RuofengX** [n0madic/twitter-scraper#103]
https://github.com/n0madic/twitter-scraper/blob/3945a8359a540575805937185ec4e5553995f7c6/util.go#L140

I think its better to change < to <=

**Comment by n0madic** [comment]
nope, since the increment increase comes after the condition for adding a tweet to the channel

**Comment by RuofengX** [comment]
But actually when I call SearchTweets(x, 5, y)， It returns only four elements in channel.  When the limit number comes to one,  The function will take no effects.

**Comment by n0madic** [comment]
Removed the remnants of the old logic - maybe this is the problem, thanks
