### ISSUE TITLE
Migrate to graphql SearchTimeline API to get GIFs from tweets

### ISSUE THREAD

**Issue by Veetaha** [n0madic/twitter-scraper#109]
# Context
It appears today Twitter's frontend uses the new endpoint for searching tweets. Its URL is this one:
```
https://twitter.com/i/api/graphql/GcjM7tlxA-EAM98COHsYwg/SearchTimeline
```

Today, the endpoint that twitter-scraper is using is
```
https://api.twitter.com/2/search/adaptive.json
```

The benefit of using the newer graphql SearchTimeline endpoint is that it delivers the GIFs from tweets. The `search/adaptive.json` have no info about the GIF media in the tweets according to my research.

The other reason to switch is because the older timeline API is probably deprecated, and may be removed at some point. The `twitter-scraper` will be safer to use the "seemingly" newer endpoint just like the current Twitter frontend does.

# Summary

The current internal implementation of SearchTweets/SearchProfiles should be changed to the newer endpoint

**Comment by n0madic** [comment]
The search now requires authorization, how about this for the new endpoint?
In addition, the `LoginOpenAccount()` only works with legacy timeline, a new endpoint will most likely require full authorization...

**Comment by Veetaha** [comment]
I see, I didn't validate the auth requirements, buts just wrote my observation. I think it makes sense to provide a SearchTweetsV2 or an additional switch on SearchTweets to enable the newer endpoint, to allow anyone who needs GIFs to use it provided they log in.

It makes sense to keep things simple for now, and expose only v1, unless there is demand for GIFs in search. As a workaround the users could search + GetTweet.

**Comment by n0madic** [comment]
While there is no request, we will leave this question open. Or until Twitter closes legacy search..
