### ISSUE TITLE
how to find pinned tweets from a specific user?

### ISSUE THREAD

**Issue by mipak** [n0madic/twitter-scraper#11]
I've tried `GetProfile()` and `GetTweets()` but I can't get the top pinned tweet of a user, which is normally displayed when I access the profile via browser/app.

With `FetchTweets(Username,"")` I get 400 Bad Request btw.

Any hints? :-)

**Comment by mipak** [comment]
seems mobile.twitter.com/username doesn't care about pinned tweets either.. tried to fetch it from there

**Comment by n0madic** [comment]
Due to the removal of the legacy API on which the scraping was based earlier, some of the information became unavailable, I could take that from other sources, such as the mobile interface, but not all so far...

**Comment by Mathiasme** [comment]
FYI : Used to have access to the legacy API, now I get "response status: 404 Not Found" on my requests. It seems recent Twitter changes to their API may penalize this project :'(

**Comment by n0madic** [comment]
Yes. had to switch to another api, not so rich in information

**Comment by Mathiasme** [comment]
Works fine for me after the update, can even get pinned information.

Thank you very much !
