### ISSUE TITLE
Problem with getting guest token

### ISSUE THREAD

**Issue by MrBoombastic** [n0madic/twitter-scraper#113]
Hi, for a few days now this library has been spitting out `Post "https://api.twitter.com/1.1/guest/activate.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)` errors. I don't know any workarounds, other than perhaps using real user authentication. Just letting you know. :)

**Comment by MrBoombastic** [comment]
Is that a duplicate of #104?

**Comment by n0madic** [comment]
no, getting a guest token is a separate process and now everything works fine for me
