### ISSUE TITLE
response status 404 Not Found

### ISSUE THREAD

**Issue by TheGrumpyT** [n0madic/twitter-scraper#115]
from today scraper.GetTweets() always returns a 
"response status 404 Not Found:"

**Comment by rado196** [comment]
The API Bearer token is defined in code constantly, jut login with your username and password before API call.

<img width="639" alt="image" src="https://github.com/n0madic/twitter-scraper/assets/24914689/ef5c3bfd-e8ea-4864-9a66-0f1fb4fdd3d5">

**Comment by revenkroz** [comment]
Twitter disabled their public web site today (2023-06-30) and require users to login

**Comment by TheGrumpyT** [comment]
Thank you :)

**Comment by thluanlx02** [comment]
What is token in source code? Do i change it?

**Comment by revenkroz** [comment]
This seems to be the end of scraping: [https://twitter.com/elonmusk/status/1675187969420828672](https://twitter.com/elonmusk/status/1675187969420828672).

```
To address extreme levels of data scraping & system manipulation, we’ve applied the following temporary limits:

- Verified accounts are limited to reading 6000 posts/day
- Unverified accounts to 600 posts/day
- New unverified accounts to 300/day
```

Two of my accounts for scraping have already been banned for a day and I can't get new tweets until tomorrow :(

**Comment by n0madic** [comment]
I made a quick dirty fix by bringing back the ability to use LoginOpenAccount with the old timeline. I don't know how fast it will be closed...

**Comment by RtiM0** [comment]
Appreciate your efforts, but loginOpenAccount no longer works. guest token API sends a `{"code":200,"message":"Forbidden."}` when we use that access token as bearer
