### ISSUE TITLE
404 on SearchTweets

### ISSUE THREAD

**Issue by amiremohamadi** [n0madic/twitter-scraper#116]
Seems like search endpoint has been changed.
![2023:07:02:15:11:08](https://github.com/n0madic/twitter-scraper/assets/31338382/5c9e1d66-f467-42f8-bbc8-b7e9bccb9e3b)

**Comment by organicinternet** [comment]
The Twitter web front end appears to have moved from adaptive.json to the GraphQL search endpoint mentioned in https://github.com/n0madic/twitter-scraper/issues/109

**Comment by muitobanco** [comment]
Any solutions to this using login or otherwise?
