### ISSUE TITLE
Bad Guest Token

### ISSUE THREAD

**Issue by tfreedman** [n0madic/twitter-scraper#119]
I have a program that looks somewhat like this:

```
package main

import (
    "os"
    "encoding/json"
    twitterscraper "github.com/n0madic/twitter-scraper"
)

func main() {
  scraper := twitterscraper.New()

  err := scraper.Login("XXX", "XXX")
  if err != nil {
    panic(err)
  }
  cookies := scraper.GetCookies()
  // serialize to JSON
  js, _ := json.Marshal(cookies)
  // save to file
  f, _ := os.Create("cookies.json")
  f.Write(js)
}
```

When run, it prints: 

```
panic: auth error (239): Bad guest token

goroutine 1 [running]:
main.main()
(reference to line 14 of the file)
```

and doesn't write out cookies.json.

However, if I remove 
  if err != nil {
    panic(err)
  }
below scraper.Login, it does actually work.

**Comment by n0madic** [comment]
can not reproduce...
disabling Login error checking does not mean that it works, then you just save junk cookies..

**Comment by tfreedman** [comment]
I should clarify, the cookies are valid and worked.
