### ISSUE TITLE
 404 and 400 code results

### ISSUE THREAD

**Issue by JustHumanz** [n0madic/twitter-scraper#12]
always return with 404 results and if use GetProfile become 400 bad request

probably twitter change frontend api (?)

**Comment by n0madic** [comment]
Quick fix https://github.com/n0madic/twitter-scraper/commit/6adc9fe0724e2648c4425a811b32faffc5004b4c

**Comment by JustHumanz** [comment]
wow, nice work sir

but there still 404 return code when use search

thx for your hardwork sir,this tools very awesome

**Comment by n0madic** [comment]
Search fixed https://github.com/n0madic/twitter-scraper/commit/23c278929418c9a32c7d0ecd274286ed996af5fd with mobile version, but not enough information retrieved...

**Comment by JustHumanz** [comment]
no problem, still better than nothing
