### ISSUE TITLE
response status 404 Not Found

### ISSUE THREAD

**Issue by devghb** [n0madic/twitter-scraper#123]
Usage:
scraper.LoginOpenAccount()

**Comment by devghb** [comment]
Usage:
scraper.LoginOpenAccount()

**Comment by devghb** [comment]
confirmation data required for LoginAcid

**Comment by n0madic** [comment]
can not reproduce

**Comment by mrbentarikau** [comment]
> can not reproduce

if one makes a new main.go and uses the code from https://github.com/n0madic/twitter-scraper#get-user-tweets
it has an error there line 12, change !== to != and you will get that 404 response error.
No proxies just that codepart.

**Comment by n0madic** [comment]
This code is working for me so far. It may be different in other locations or countries...
We must wait until Twitter stops perturbations.
