### ISSUE TITLE
set proxy with auth required

### ISSUE THREAD

**Issue by aero89** [n0madic/twitter-scraper#143]
```
if strings.HasPrefix(proxyAddr, "socks5") {
		baseDialer := &net.Dialer{
			Timeout:   s.client.Timeout,
			KeepAlive: s.client.Timeout,
		}
		socksHostPort := strings.ReplaceAll(proxyAddr, "socks5://", "")
		dialSocksProxy, err := proxy.SOCKS5("tcp", socksHostPort, &proxy.Auth{username:"uname", password:"pass"}, baseDialer)
		if err != nil {
			return errors.New("error creating socks5 proxy :" + err.Error())
		}
		if contextDialer, ok := dialSocksProxy.(proxy.ContextDialer); ok {
			dialContext := contextDialer.DialContext
			s.client.Transport = &http.Transport{
				DialContext: dialContext,
			}
		} else {
			return errors.New("failed type assertion to DialContext")
		}
		s.proxy = proxyAddr
		return nil
	}
```

**Comment by bkuhl** [comment]
You need to provide some extra context on why you opened this issue and what this code is for.

**Comment by laikee99** [comment]
> You need to provide some extra context on why you opened this issue and what this code is for.

I believe he wants a PR.

**Comment by aero89** [comment]
I don't need pr, I use your package and use a proxy with authorization, but your package did not provide authorization at the time of writing the problem that I opened. The code only shows where you need to add authorization for the socks5 protocol

**Comment by bkuhl** [comment]
@aero89 awesome, I think it can be a good idea to share things like that in issues from time to time. But if there's no ongoing something that needs to be solved here I think it would be a good idea to close the issue which would leave your code here as a point of reference for other folks.
