### ISSUE TITLE
How can I get user's whole timeline?

### ISSUE THREAD

**Issue by Akitora-R** [n0madic/twitter-scraper#15]
It seems same as twitter's api, can only get about 3200 tweets for one user.
How can I get user's whole timeline?

**Comment by n0madic** [comment]
Hmm, try the function [FetchTweets](https://godoc.org/github.com/n0madic/twitter-scraper#FetchTweets) with the last tweet received

**Comment by Akitora-R** [comment]
thanks for replying.
But I tried with this older tweet id, it returns an empty list.
However, it works fine with newer id...
```go
func TestGetTimeline3(t *testing.T) {
	oldId:="1182611770541658112"
	//newId:="1316016708373544964"
	tweets, err := twitterscraper.FetchTweets("shi_ha_chi", oldId)
	if err != nil {
		panic(err)
	}
	for _, tweet := range tweets {
		log.Println(tweet.ID)
	}
}
```

**Comment by n0madic** [comment]
So you have reached the limit for this API ...

**Comment by Akitora-R** [comment]
so...is there have any way to bypass this limit?
will this happen in python ver Twitter Scraper?

**Comment by n0madic** [comment]
This is a Twitter API limitation...

You can try searching from a specific date:
`from:shi_ha_chi until:2015-12-21`
