### ISSUE TITLE
GetTweets without replies

### ISSUE THREAD

**Issue by moson-mo** [n0madic/twitter-scraper#16]
Hi,

Could we change the functions GetTweets and FetchTweets and a bool parameter "withReplies" ?
Right now it will fetch reply tweets as well:

`q.Add("with_replies", "true")`

Alternative would be to add "IsReply" to the Tweet struct, but not sure if that information is contained in the html, didn't check yet.

regards,
mo

*edit*
I can make a pull request with the changes, but first wanted to check with you if it would be ok.

**Comment by n0madic** [comment]
Adding any additional options will break the API, so the only way out is to add the IsReply tweet property

**Comment by n0madic** [comment]
https://github.com/n0madic/twitter-scraper#load-timeline-with-tweet-replies

**Comment by n0madic** [comment]
Added a method for this
```golang
twitterscraper.WithReplies(true)
```
