### ISSUE TITLE
Issues about HTML field

### ISSUE THREAD

**Issue by LarchLiu** [n0madic/twitter-scraper#18]
The latest version is perfect, i can get more content than before. 
But at tw.HTML field  the regular expression of user name (reUsername) is missing the digit rules,  such as @RonaldAraujo939 can't be matched.

And some emoji that defined by Twitter can't be displayed. I remember that the previous version had image resources of emoji.

![WX20201218-180210](https://user-images.githubusercontent.com/4410452/102601614-622edd80-415b-11eb-96ab-9e3b52411bd1.png)
![WX20201218-175733](https://user-images.githubusercontent.com/4410452/102601630-66f39180-415b-11eb-9177-6ad6de850ade.png)

**Comment by LarchLiu** [comment]
And the regex of reHashtag cannot be matched #BarçaRealSociedad

**Comment by n0madic** [comment]
FIXED 
https://github.com/n0madic/twitter-scraper/commit/9322ebbc3708210bfa72c2e783c0d9d872cae61f
https://github.com/n0madic/twitter-scraper/commit/0275c93c3738d3e42c055e75e92183fce9a00404

**Comment by n0madic** [comment]
Emojis in the Text field are also not displayed?

**Comment by LarchLiu** [comment]
I found that emojis can be displayed on a Windows PC, but it does not work on my Mbp. Maybe it's an OS problem? My MacOS is still 10.13.6

b.t.w the Text field is the same to that. You can check it on http://cloudgeektech.com/gh-twitter/, it is a gh-page for test.

**Comment by LarchLiu** [comment]
At util.go line 179
return fmt.Sprintf(`<a href="%s">%s</a>`, entity.ExpandedURL, tco)
should change to
return fmt.Sprintf(`<a href="%s">%s</a>`, tco, entity.ExpandedURL)

**Comment by n0madic** [comment]
everything is correct - this is so as not to change the text of the tweet, and the link is already expanded
