### ISSUE TITLE
sample code turns to return 400 Bad Request

### ISSUE THREAD

**Issue by kohey** [n0madic/twitter-scraper#20]
Hi,

The sample code you provide on README turns to return 400 bad request **since last week.**
I'm running similar code on AWS EC2 instance and cron every week.

I confirm this code worked since **12/13(SUN)**.
Any changes on Twitter frontend API?

```
package main

import (
	"context"
	"fmt"
	twitterscraper "github.com/n0madic/twitter-scraper"
)

func main() {
	for tweet := range twitterscraper.SearchTweets(context.Background(),
		"twitter scraper data", 50) {
		if tweet.Error != nil {
			panic(tweet.Error)
		}
		fmt.Println(tweet.Text)
	}
}

=> panic: response status: 400 Bad Request

```
regards,

**Comment by n0madic** [comment]
I recently did a complete parsing refactoring - now using the official guest API, try the latest copy of the repository code

**Comment by kohey** [comment]
The latest version worked perfectly, thanks!
