### ISSUE TITLE
User timeline don't include pin tweet

### ISSUE THREAD

**Issue by allanpk716** [n0madic/twitter-scraper#23]
when i first time to get someone's tweets, timeline won't include user pin tweet.

**Comment by n0madic** [comment]
Can I have an example of such a timeline?

**Comment by allanpk716** [comment]
> Can I have an example of such a timeline?

timeline for Twitter ID:baby_eiss

**Comment by n0madic** [comment]
The pinned tweet is a separate entity from the timeline, I don't even know where to insert it better..
