### ISSUE TITLE
HashTag Scraping with metadata

### ISSUE THREAD

**Issue by wraza2k9** [n0madic/twitter-scraper#31]
While hashtag scraping how can I get metadata i.e. 'Created at' and user information(Handle, Screen Name) for each tweet?

**Comment by n0madic** [comment]
An example of your code please

**Comment by wraza2k9** [comment]
I mean using your 'scraper.getTweets() API, how can I get a tweet's metadata?

**Comment by n0madic** [comment]
You can get this metadata https://pkg.go.dev/github.com/n0madic/twitter-scraper#Tweet

**Comment by wraza2k9** [comment]
Using <scraper.SearchTweets(context.TODO(), '#abc',10)> I am only able to get tweet text, how to get tweet id along with text?, can you assist in this regard, please.

**Comment by n0madic** [comment]
```go
for tweet := range scraper.SearchTweets(context.TODO(), "#abc", 50) {
	fmt.Println(tweet.ID, tweet.Text)
}
```

**Comment by wraza2k9** [comment]
It works, thanks a lot.
