### ISSUE TITLE
Description claims "No tokens needed", yet `api.go` contains a token

### ISSUE THREAD

**Issue by playfulpachyderm** [n0madic/twitter-scraper#33]
The README says in the first paragraph that no tokens are needed.  What is the function of the `bearerToken` in `api.go`?  Can it just be used as-is, or should it be replaced with something?  

There is also a `guestToken` field on the Scraper, though it looks like this can be refreshed any time, so it presumably doesn't have much significance.

**Comment by n0madic** [comment]
This means that user tokens are not needed. The guest token is obtained automatically the first time you open the Twitter website without logging in using the `bearerToken` that is hardcoded.
