### ISSUE TITLE
Geo Location along with a tweet

### ISSUE THREAD

**Issue by wraza2k9** [n0madic/twitter-scraper#36]
How can I get geolocation along with a tweet? because there is no such field exists in the tweet struct.
Please consider this.

**Comment by n0madic** [comment]
Can you give an example of such a tweet and what kind of geo information you need to extract?

**Comment by wraza2k9** [comment]
Twitter saves user location (i.e. sent from browser/device) along with the tweets, if the location feature enabled in the user's security settings. In this case, when you extract the contents of the Twitter in response to the API call should check any field that contains the geo Location with each tweet. 
For details please visit:
https://help.twitter.com/en/safety-and-security/tweet-location-settings

**Comment by n0madic** [comment]
Please provide a link to a specific tweet with location

**Comment by wraza2k9** [comment]
The following link demonstrates example query and response:
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets

**Comment by n0madic** [comment]
This library does not use the official Twitter API, I need a link to a specific tweet with a location
