### ISSUE TITLE
Not getting userid or name who retweeted

### ISSUE THREAD

**Issue by wraza2k9** [n0madic/twitter-scraper#37]
SearchTweets function only returns the userid or name of the person who creates the tweet. It does not return the username/id of the person who retweets

Can you provide the example use of Retweet Struct?

Thanks.

**Comment by n0madic** [comment]
timeline is parsed like everywhere else, it should be in theory ..
please give a piece of code with your search

**Comment by wraza2k9** [comment]
> timeline is parsed like everywhere else, it should be in theory ..
> please give a piece of code with your search

for tweet := range scraper.SearchTweets(context.Background(), query, num_of_tweets) {
       tweets := []string( tweet.ID,  tweet_timeparsed,  strconv.Itoa(tweet.Likes),   strconv.Itoa(tweet.Replies),strconv.Itoa(tweet.Retweets), tweet.Text, : tweet.UserID,  tweet.Username, tweet.Retweet.UserID,
			 tweet.Retweet.Username)
}

**Comment by wraza2k9** [comment]
'GetTweets' function parses retweets,  'SearchTweets' does not. Can you check the code?

**Comment by n0madic** [comment]
they both use the parsing function [parseTimeline](https://github.com/n0madic/twitter-scraper/blob/master/util.go#L181)..
more interested in the value of the `query` parameter

**Comment by n0madic** [comment]
Try add to search query `filter:nativeretweets`

**Comment by wraza2k9** [comment]
Yes, getting retweets only by using the filter. But wants to get both 'regular' and 'retweet' in a single query.
Thanks.

**Comment by n0madic** [comment]
This filter shows that the user's data is retrieved if there is a retweet.
As I understand it, the default search does not show retweets at all.

**Comment by wraza2k9** [comment]
ok, I will manage through code.

**Comment by wraza2k9** [comment]
Thanks, for your support.
