### ISSUE TITLE
Sorry, that page does not exist.

### ISSUE THREAD

**Issue by bluebabes** [n0madic/twitter-scraper#39]
tweet, err := scraper.GetTweet("907700934486003712")
	if err != nil {
		log.Println(err)
	}
	fmt.Println(tweet.Text)

result is error

2021/07/04 15:22:32 response status 404 Not Found: {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x127f024]

**Comment by n0madic** [comment]
Perhaps the tweet with this ID is gone? With another ID, I have everything ok..

**Comment by bluebabes** [comment]
Oh, Sorry. it's ok 

i'am was wrong with use  user id to single tweet func
