### ISSUE TITLE
how to connect tweet and its reply?

### ISSUE THREAD

**Issue by wraza2k9** [n0madic/twitter-scraper#40]
Getting tweets with replies? but don't understand how to connect a tweet with its reply? Because I did not find any field in the 'Tweet' struct for the same.
 Please provide a solution.

**Comment by n0madic** [comment]
try `tweet.InReplyToStatus`

**Comment by wraza2k9** [comment]
getting <nil> value while accessing the field 'tweet.InReplytoStatus'.

**Comment by wraza2k9** [comment]
getting 'nil' value while accessing the field 'tweet.InReplytoStatus'.

> getting value while accessing the field 'tweet.InReplytoStatus'.

getting 'nil' value.

**Comment by n0madic** [comment]
So this tweet is not a reply.

**Comment by wraza2k9** [comment]
Even in the case of a reply, it returns <nil>.

**Comment by n0madic** [comment]
[This](https://github.com/n0madic/twitter-scraper/blob/master/tweets_test.go#L125) test checks a tweet that is a reply and InReplyToStatus refers to the parent tweet.

**Comment by wraza2k9** [comment]
please give an example of how to use 'tweet.InReplytoStatus '

**Comment by n0madic** [comment]
`tweet.InReplytoStatus` have `Tweet` type, I don't understand what the problem is ...

**Comment by n0madic** [comment]
Or do you need to receive a tweet and all its conversations? This is not implemented ..

**Comment by wraza2k9** [comment]
It works with the 'GetTweets' function but doesn't with 'SearchTweets'

**Comment by n0madic** [comment]
`GetTweets` retrieves the user's timeline, `SearchTweets` does a keyword search - these are very different methods

**Comment by wraza2k9** [comment]
OK.
Thanks :)

**Comment by wraza2k9** [comment]
It would be great, if the same functionality is implemented with the 'SearchTweets' function.
