### ISSUE TITLE
Interested in contributing to this project

### ISSUE THREAD

**Issue by brijeshshah13** [n0madic/twitter-scraper#45]
Hey @n0madic, is there any feature or an issue that needs to be developed for this project. I would like to contribute to the same.

**Comment by brijeshshah13** [comment]
@n0madic Sure. Would be glad to pick it up. I am going through the current implementations of different functionalities. I also have some queries related to the same. Do we have a discord server or something to communicate easily? If not, I would be grateful if you can create one, I would like to learn and contribute more to your projects.

**Comment by n0madic** [comment]
I don't use discord.. Maybe telegram or gitter?

**Comment by brijeshshah13** [comment]
Sure. Telegram works. Please share whatever link is required to join. If it's confidential, you can share it on brijeshjain13@gnail.com

**Comment by n0madic** [comment]
Check mail

**Comment by brijeshshah13** [comment]
@n0madic Had a typo in the mail id. wrote gnail instead of gmail. Please send again.
