### ISSUE TITLE
Implement authorization using login and password

### ISSUE THREAD

**Issue by n0madic** [n0madic/twitter-scraper#46]
To access private tweets, full authorization is required instead of a guest token

**Comment by DarkWingMcQuack** [comment]
if this is implemented could retweets, likes and comments also be supported theoretically?

**Comment by n0madic** [comment]
theoretically everything that can be done on the site is possible, but I have no practical need for this, pull requests are welcome

**Comment by n0madic** [comment]
[implemented](https://github.com/n0madic/twitter-scraper/commit/6d13e319a39d942f0f4b9c1ba6ad0b89f328680a)
