### ISSUE TITLE
Getting just few tweets and no more.

### ISSUE THREAD

**Issue by jpadula** [n0madic/twitter-scraper#47]
Hello, I'm trying to scrape tweets of an user using FetchTweets but I have an issue. I have something like this (that is working, but limited)
```go
maxTweetsNbr := 22500 // qty of tweets of user
tweetsNbr := 0
nextCursor := ""
okToContinue := true

for tweetsNbr < maxTweetsNbr &&  okToContinue {
    tweets, cursor, err := scraper.FetchTweets(username, 200, nextCursor)
    if err != nil {
        fmt.Println(err.Error())
    }
    for _, tweet := range tweets {
        _, err = tweetsCollection.InsertOne(context.TODO(), tweet)
        if err != nil {
            fmt.Println("Error profilesCollection.UpdateOne: ", err.Error())
            return nil, err
        }
    }
    okToContinue = err == nil && cursor != nextCursor && cursor != "" && len(tweets) > 0

    tweetsNbr += len(tweets)
    nextCursor = cursor

    fmt.Println("page ok: ", tweetsNbr)
}
```
Issue is that len(tweets) always in the same point is 0 (so just its pulling for example 853 tweets (of 22k approx) and then no more tweets are retrieved). I just tried with proxy and withDelay but not luck

If I try another twitter account (of 88k of tweets) the same, just is pulling for example 900 tweets and then no more (even if I retry many times)

**Comment by n0madic** [comment]
Better use the `GetTweets` function, `FetchTweets` are more for internal use ...
Twitter Frontend API has a limit on the number of maximum tweets received for a guest account, when I tested that limit was about 3200, maybe it was reduced now.
Alternatively, you can try searching with limited dates:
`from:twitter_account until:2020-12-31`

**Comment by jpadula** [comment]
So the idea is to get the historical tweets for example. how do you think would be the code using GetTweets and cursor to get all (or at least the maximum as possible)?

**Comment by n0madic** [comment]
`GetTweets` will receive all possible tweets until the server stops sending them (just set the limit as much as possible).
I suggested above to try using `SearchTweets` by setting the date of the last received tweet to `until`.
