### ISSUE TITLE
Multiple query filters

### ISSUE THREAD

**Issue by jonreesman** [n0madic/twitter-scraper#49]
Love the library. Implementing it in my first Go project right now. I am having the issue where I cannot use multiple filters in a query such as:

```...SearchTweets(context.Background(), "NASA -filter:retweets within_time:1h",50)```

Now obviously NASA is frequently tweeted about, but if I choose something like JASMY, it gives me tweets from outside the hour. I've used this same exact string literal in the Twitter search bar and it seems to function properly there. Am I missing something from your documentation? It seemed to me that we could use the exact same queries as on Twitter itself.

**Comment by n0madic** [comment]
Does your regular Twitter search return the same results?

**Comment by jonreesman** [comment]
No, it returns tweets that are within the last hour. The tweets returned from the twitterscraper library do not take this filter into account for some reason.

**Comment by n0madic** [comment]
Try to sort the results
```go
scraper.SetSearchMode(twitterscraper.SearchLatest)
```

**Comment by jonreesman** [comment]
That is presently what I am working with:
```

scraper.SetSearchMode(twitterscraper.SearchLatest)
for tweet := range scraper.SearchTweets(context.Background(), t.Name + "-filter:retweets within_time:1h", 50) {
```

Have you been able to make it function properly on your end?

**Comment by n0madic** [comment]
Yes, without `-filter:retweets`...
Try 
```go
scraper.WithReplies(false)
```

**Comment by jonreesman** [comment]
That appears to have done the trick. Thank you!
