### ISSUE TITLE
support for interaction when used with cookies

### ISSUE THREAD

**Issue by DarkWingMcQuack** [n0madic/twitter-scraper#52]
would it be possible to implement `follow`, `retweet` and so on when used with cookies?

**Comment by n0madic** [comment]
theoretically everything that can be done on the site is possible, but I have no practical need for this, pull requests are welcome

**Comment by amirkhaki** [comment]
@n0madic 
Could you add a tutorial or something alike, about how to add functionalities of the site in the library? A contribution starter guide.

**Comment by n0madic** [comment]
sorry, no time for this
You need to explore the Twitter site in a browser with devtool and implement it on Go
