### ISSUE TITLE
error in getting username of tweet reply

### ISSUE THREAD

**Issue by wraza2k9** [n0madic/twitter-scraper#59]
The code   "tweet.InReplyToStatus.Username" generates an error while accessing the tweet of type 'reply'.

Please check and assist to resolve the problem.
Thanks.

**Comment by n0madic** [comment]
Can you give me an example of code that doesn't work?

**Comment by wraza2k9** [comment]
Code:
1. scraper := twitteracraper.New()
2. scraper.WithReplies(true)
3. 
4. for tweet := range scraper.GetTweets(context.Background(), some_user, 50)  {
5.     if(tweet.isReply) {
6.                 fmt.Println("Reply Tweet")
7.                 fmt.Println(tweet.InReplyToStatus.Username)
8.      }
9. }

getting runtime error "invalid memory address or nil pointer", line 7: of above code

**Comment by n0madic** [comment]
for this error need more check for nil
```go
if tweet.isReply && tweet.InReplyToStatus != nil {
```
but I wonder why it doesn’t parse fully, need the tweet.ID on which the scraper falls

**Comment by wraza2k9** [comment]
'tweet.isReply' is not nil. 
However, 'tweet.InReplyToStatus' is nil.  
It seems that there is some parsing issue.

**Comment by n0madic** [comment]
so I'm waiting for the troubled tweet ID

**Comment by wraza2k9** [comment]
Tweet ID: 1517988099451621377

**Comment by n0madic** [comment]
It's not reply - it's quoted tweet

**Comment by wraza2k9** [comment]
You are right, can you guide me on how to get the username of that tweet i.e. quoted tweet.
Thanks.

**Comment by wraza2k9** [comment]
The reply tweet ID:  "1517876846666211328".

**Comment by wraza2k9** [comment]
I have checked with another account but the problem is the same:
"tweet.InReplyToStatus.Username" returns "runtime error: invalid memory address or nil pointer dereference".

The tweet id is:
Reply tweet
1517879766585847808
