### ISSUE TITLE
Runtime Error while getting the username of the tweet having "Quote' status

### ISSUE THREAD

**Issue by wraza2k9** [n0madic/twitter-scraper#60]
Tweet id:
1526895928942030848

Getting runtime error while getting the username of the above tweet via code:
"quote_user_profile, err := scraper.GetProfile(tweet.QuotedStatus.Username)"

**Comment by n0madic** [comment]
It's not quoted status
`tweet.QuotedStatus: nil`
Add check
```go
if tweet.QuotedStatus != nil {
  ...
}
```
