### ISSUE TITLE
Bad Guest Token Without `X-Csrf-Token`

### ISSUE THREAD

**Issue by gabe565** [n0madic/twitter-scraper#64]
Hello! Love the work you've done on this library. I'm hoping this breaking change can be worked around, but I'm nervous at the moment.

Beginning today, my scrapes always return `Bad guest token`. I copied some API calls from my browser as curl, then removed headers to match what gets set by this library. Responses started breaking when I removed the `X-Csrf-Token` header, leading me to believe this header is now required for guests. Without it, my curl calls get the same `Bad guest token` error.

So far, I haven't had any luck finding the token. I suspect it's obfuscated somewhere in one of the inline HTML `<script>` tags, but the amount of minification makes it tough to locate.

**Comment by n0madic** [comment]
Hello.
I haven't been able to reproduce this problem yet..
In addition, tests are run every day in [CI](https://github.com/n0madic/twitter-scraper/actions/workflows/go.yml) and there have been no errors yet.

**Comment by gabe565** [comment]
Ok that's good news! My HTTP endpoints are working again so maybe Twitter's API had some sort of a partial outage. Sorry for the trouble!
