### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by prologic** [n0madic/twitter-scraper#65]
Are you aware of any issues using your library? Such as (for example):

```
error="error scraping tweets from gtdguy: response status 429 Too Many Requests: "
```

See: https://git.mills.io/yarnsocial/feeds/issues/24

**Comment by n0madic** [comment]
I do not use this library so intensively, because such an error almost never comes across. most likely, the rate limit for the frontend is triggered - I can only advise using proxies

**Comment by prologic** [comment]
Do you have any idea what the rate limit is for the front end?

**Comment by n0madic** [comment]
Nope

**Comment by prologic** [comment]
Ok 😅 Me neither... Contemplating continuing to support this feature or not... 🤔 Thanks for the quick response 🙇‍♂️
