### ISSUE TITLE
setBearerToken is private

### ISSUE THREAD

**Issue by Muratthekus** [n0madic/twitter-scraper#69]
`
func (s *Scraper) setBearerToken(token string) {
	s.bearerToken = token
	s.guestToken = ""
}`

setBearerToken method is private. Shouldn't it be public?

**Comment by n0madic** [comment]
should not, since the guest bearer token is [static](https://github.com/n0madic/twitter-scraper/blob/968dc0c61f374f914ed44c15a5b0d703733f6dc5/api.go#L11) and the method is used internally
