### ISSUE TITLE
scraper.SearchTweets() can it return expanded URLs instead of t.co, without additional network calls?

### ISSUE THREAD

**Issue by olokos** [n0madic/twitter-scraper#71]
Hey there,

First of all, amazing work, this project is really cool and useful!

I need one functionality, but I'm not yet sure how to approach this the best way.
```
func main() {
    scraper := twitterscraper.New()
    for tweet := range scraper.SearchTweets(context.Background(),
        "twitter scraper data -filter:retweets", 50) {
        if tweet.Error != nil {
            panic(tweet.Error)
        }
        fmt.Println(tweet.Text)
    }
}
```

Can this somehow, perhaps by some existing parameter, output links in the full-expanded form?
I see that there's `tweet.HTML`, but then parsing this and getting the URLs would be a pain.

Perhaps there's already some feature, that would allow me to use `scraper.SearchTweets()` and get output with full-URLs, without changing the original library source code?

If not, could You please point me to a place in the existing code, where I could implement this parameter myself with the least impact on performance/least changes to codebase?

Thank You very much for Your work once again!

**Comment by olokos** [comment]
I see that there's also `tweet.URLs` which does contain an array of URLs within the twiter text, which is amazing.

I was thinking, that maybe it could be possible to display `tweet.Text`, but keeping the original tweet text, exactly as displayed on twitter's website or keeping the URLs in same form as `tweet.URLs`.

Perhaps something like `tweet.OriginalText` or `tweet.TextFullLinks`?
So the first would display links exactly as displayed on the website "https://somewebsite..."
The second could display links in the expanded form like "https://somewebsite.com/somesubsite"

Could this be considered as a potential new feature of the library, or it's unlikely that it will be included in the original repo source?

**Comment by n0madic** [comment]
I don't need this functionality so I don't plan to add it yet. You can create a pull request and I will review it.

**Comment by olokos** [comment]
Thank You for blazing fast reply.
Have a wonderful day!
