### ISSUE TITLE
scraper.SearchTweets Missing or invalid url parameter 

### ISSUE THREAD

**Issue by 0xfaceDEFI** [n0madic/twitter-scraper#74]
Request:  scraper.SearchTweets

Error : Get "https://twitter.com/i/api/2/search/adaptive.json?cards_platform=Web-12&count=5&cursor=DAACCgACFrUoErMAJxAKAAMWtSgSsv_Y8AgABAAAAAILAAUAAABIRW1QQzZ3QUFBZlEvZ0dKTjB2R3AvQUFBQUFRV3RSZW9HTllBQUJhMHJwNlZGNEFERnJPTGpRTFhzQUFXdEQydnN0ZkFBUT09CAAGAAAAAAgABwAAAAAMAAgKAAEWs4uNAtewAAAAAA&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2CbirdwatchPivot%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe&include_blocked_by=1&include_blocking=1&include_can_dm=1&include_can_media_tag=1&include_cards=1&include_entities=true&include_ext_alt_text=true&include_ext_collab_control=true&include_ext_edit_control=true&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_limited_action_results=false&include_ext_media_availability=true&include_ext_media_color=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&include_ext_verified_type=1&include_ext_views=true&include_followed_by=1&include_mute_edge=1&include_profile_interstitial_type=1&include_quote_count=true&include_reply_count=1&include_tweet_replies=false&include_user_entities=true&include_want_retweets=1&pc=1&q=WatcherGuru&query_source=typed_query&requestContext=launch&send_error_codes=true&simple_quoted_tweet=true&skip_status=1&spelling_corrections=1&tweet_mode=extended"

Error info : {"errors":[{"code":47,"message":"Missing or invalid url parameter."}]}

Do you have any advice on how to fix it, bro?

**Comment by 0xfaceDEFI** [comment]
> Please Upload Codes With Issues Too !!

<img width="970" alt="image" src="https://user-images.githubusercontent.com/84782631/227828395-a25b4cee-af0b-44ef-973b-31c2460abab2.png">

**Comment by n0madic** [comment]
can't reproduce this problem
