### ISSUE TITLE
Some users are not fetched

### ISSUE THREAD

**Issue by flockin** [n0madic/twitter-scraper#8]
I'm having an issue with fetching some users; i.e fetching `@flockinco` doesn't seem to work.

Many others I've tried do work, but this one specifically doesn't. Anything I can do to debug this?

Thanks!

**Comment by n0madic** [comment]
The location is not specified in the profile - and this field is used to [check](https://github.com/n0madic/twitter-scraper/blob/master/profile.go#L58) the existence of the user ...

**Comment by flockin** [comment]
Interesting....maybe just check by another field? Would that work?

**Comment by n0madic** [comment]
[Extended user validity check](https://github.com/n0madic/twitter-scraper/commit/a1bf646b85f02c7b0697019b36e7f6ab7c08e0d8)

**Comment by flockin** [comment]
@n0madic Fantastic! Thanks so much for quick turnaround.
