### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by rwiim-k** [n0madic/twitter-scraper#80]
Hello! Something seems to have changed in the authentication process, I'm having 403 error (token expired?)

**Comment by n0madic** [comment]
Twitter sometimes bans for too frequent requests - try proxy or change ip

**Comment by rwiim-k** [comment]
Tried with new IPs from 2 different locations and same error:
Status code=403, Body={"errors":[{"code":200,"message":"Forbidden."}]}

**Comment by rwiim-k** [comment]
Thanks. It worked once and now I have "auth error (366): Required input 'LoginEnterAlternateIdentifierSubtask' not provided."

**Comment by WhereTheTimeWent** [comment]
> Thanks. It worked once and now I have "auth error (366): Required input 'LoginEnterAlternateIdentifierSubtask' not provided."

I had the same error message when I tried to authenticate with email. Use username instead.
