### ISSUE TITLE
Get Authenticated User's timeline

### ISSUE THREAD

**Issue by regalialong** [n0madic/twitter-scraper#82]
Now that 6d13e319a39d942f0f4b9c1ba6ad0b89f328680a is implemented, would it be possible to fetch the home of the user we logged into as? I can understand if you might not be interested in this, this would allow using twitter-scraper to develop an alternative to the web frontend.

**Comment by regalialong** [comment]
Using the following code:
```golang
package main

import (
	"context"
	"fmt"
	twitterscraper "github.com/n0madic/twitter-scraper"
)

const (
	username = ""
	password = ""
)

func main() {
	scraper := twitterscraper.New()
	err := scraper.Login(username, password)
	if err != nil {
		panic(err)
	}

	for tweet := range scraper.GetTweets(context.Background(), username, 20) {
		if tweet.Error != nil {
			panic(tweet.Error)
		}
		fmt.Println(tweet.Text)
	}
}
```

I get `panic: response status 429 Too Many Requests: `, I'm able to fetch `Twitter` without login though which makes me wonder if I'm experiencing the same issue as #85.
I've also let a friend run the same code and it happens there too.

**Comment by n0madic** [comment]
It looks like GetTweets doesn't work at all on login..
