### ISSUE TITLE
[Question] How to iterate with SearchTweets?

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [n0madic/twitter-scraper#83]
How do I use SearchTweets in an iterative way, so I will be able to go over older tweets? 
For example: query := "from:elonmusk filter:media"

**Comment by a-l-e-x-d-s-9** [comment]
I've started using "until:" in a query. So I go from today, pull 50 tweets, and find the tweet with the oldest date. Then change the until to the oldest day minus one day, and pull more tweets with a new query. It seems to work fine for me.
Is there another way to do it, possibly a better solution?

**Comment by Arf9999** [comment]
In *theory* it should be possible to page the queries by final tweet returned. i.e. automate the scraper to look for the next 50 results.  Maybe request this as a an upgrade. The {snscrape} python  package used to do this, but it no longer works due to auth issues.

**Comment by stevestavropoulos** [comment]
Twitter suggests using max_id for pagination. You get 50 results, look at the id of the last returned result and then do a search again with the same query appended with max_id:thelastid

**Comment by kuwakuwi1** [comment]
Hi, how to append max_id in GetTweets function?
