### ISSUE TITLE
[Suggestion] Get if tweet is in a thread and the thread tweets

### ISSUE THREAD

**Issue by Xpl0itU** [n0madic/twitter-scraper#84]
The python tweety-ns package does this, so it's possible to do [https://pypi.org/project/tweety-ns/](https://pypi.org/project/tweety-ns/)

**Comment by n0madic** [comment]
Use `scraper.GetTweet` for parrent tweet and check `IsSelfThread` and `Thread` list

**Comment by Xpl0itU** [comment]
Thanks so much, just a few questions:
- does the Thread list also contain the parent tweet?
- if you supply a tweet which is, let’s say, the third tweet in a thread, what would happen? The list contains all the tweets except the chosen one, has all of them or only the tweets below the chosen?
