### ISSUE TITLE
twitterscraper.SearchLatest is not working

### ISSUE THREAD

**Issue by tiklup11** [n0madic/twitter-scraper#87]
twitterscraper.SearchLatest is not working

```
func getTweets(hashtags string) ([]byte, error) {
	scraper := twitterscraper.New()
	scraper.SetSearchMode(twitterscraper.SearchLatest)
	_ = scraper.Login("username", "pass")
	log.SetOutput(os.Stdout)
	log.SetLevel(log.DebugLevel)

	body := []string{}

	for tweet := range scraper.SearchTweets(context.Background(),
		hashtags, 10) {
		if tweet.Error != nil {
			return nil, tweet.Error
		}
		body = append(body, tweet.Text)
	}
	response := Response{body}
	fmt.Print(response)
	return json.Marshal(response)
}
```

**Comment by MiddleRed** [comment]
Same, seems Alexander has tried to manage it but failed. Waiting for a fix.

**Comment by n0madic** [comment]
i try [fix](https://github.com/n0madic/twitter-scraper/commit/fb7a0065f4ec6d26221991389fc047f171caaba3) this

**Comment by clownfish2023** [comment]
Is this issue solved?

**Comment by MiddleRed** [comment]
> Is this issue solved?

Yes, though it may cast a csrf error if it continuously fetches tweets as I have tested

**Comment by clownfish2023** [comment]
> > Is this issue solved?
> 
> Yes, though it may cast a csrf error if it continuously fetches tweets as I have met before probably already became more stable after some new commits but I haven't tried.

Why does my program report this error “unexpected end of JSON input”?
