### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by clownfish2023** [n0madic/twitter-scraper#96]
I use the latest version to search, but reported this error "unexpected end of JSON input".
github.com/n0madic/twitter-scraper v0.0.0-20230510192940-b65855f49dc

```go
scraper.SetSearchMode(twitterscraper.SearchLatest)
for tweet := range scraper.SearchTweets(context.Background(), tweetQuery, 100) {
                if tweet.Error != nil {
                        log.Println("search error:",tweet.Error)
                        continue
                }
}
```

**Comment by n0madic** [comment]
did you log in before using?
search now does not work without authorization ..

**Comment by nick-zkp** [comment]
> did you log in before using? search now does not work without authorization ..

Yes,I'm already logged in

**Comment by clownfish2023** [comment]
> did you log in before using? search now does not work without authorization ..

Yes,i'm already logged in.

**Comment by clownfish2023** [comment]
I think it may be that the latest go package has not been released, because I use “git pull” get the latest code, and then run the search_test use case is ok, but this error will occur when using the released package

**Comment by n0madic** [comment]
I can not reproduce - I have a search without problems ..
scraper.IsLoggedIn() == true ?

**Comment by clownfish2023** [comment]
> 

It's false.Do I need to log in with a developer account? I made a mistake earlier and used my personal account to log in

**Comment by n0madic** [comment]
You must log in as user, like on Twitter site

**Comment by clownfish2023** [comment]
> You must log in as user, like on Twitter site

At the beginning, when I log in with my personal account, I will report this error “37 Your credentials do not allow access to this resource”，then  I set my account to remove 2fa authentication，now report "auth error (399): Incorrect. Please try again"

**Comment by n0madic** [comment]
in browser you log in without problem and email verification?

**Comment by clownfish2023** [comment]
> in browser you log in without problem and email verification?

There is no problem logging in on chrome, you only need to fill in the user name, password, and email address to log in successfully

**Comment by clownfish2023** [comment]
> Both logins on same computer? If you have email confirmation, use email address in addition:
> 
> ```go
> err := scraper.Login("username", "password", "email")
> ```

The error occurred is running on the ubuntu server.Can this still be supported?

**Comment by n0madic** [comment]
It looks like Twitter is blocking requests from strange places like datacenters, so I can't set up CI in GitHub Action...

**Comment by zada-fi** [comment]
> It looks like Twitter is blocking requests from strange places like datacenters, so I can't set up CI in GitHub Action...


Is there any way to solve it?

**Comment by clownfish2023** [comment]
> It looks like Twitter is blocking requests from strange places like datacenters, so I can't set up CI in GitHub Action...

Is there any way to solve it?

**Comment by clownfish2023** [comment]
> maybe try using a proxy..

I changed a cloud host and it works now
