### ISSUE TITLE
Can posting tweets be implemented

### ISSUE THREAD

**Issue by ExHix** [n0madic/twitter-scraper#98]
I know this is not the function this tool is supposed to do, but it would be greatful if posting tweets can be implemented, for i can hardly bear the limitation of Twitter's official api and feel sh*t to open a browser and use selenium to post a tweet everytime.

**Comment by n0madic** [comment]
this is definitely not a scraper function and its implementation is comparable to writing a new library, therefore it is not within the framework of this project
